version: '3'
services:
  hyperf-skeleton:
    container_name: hyperf-skeleton
    image: hyperf-skeleton
    working_dir: /app
    build:
      context: .
    entrypoint: sh
    volumes:
      - ./:/app
    ports:
      - 9501:9501
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false

networks:
  default:
    name: hyperf-skeleton
